[package]
name = "rustsummit2"
version = "0.1.0"
edition = "2024"

[dependencies]
impl-trait-for-tuples = "0.2.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
typetag = "0.2.20"
